please mount google drive before you begin

# Part I: Set-up and Data Processing

In [1]:
cd /content/drive/MyDrive/DEX_Uniswap_Layer2/Poly

/content/drive/MyDrive/DEX_Uniswap_Layer2/Poly

In [2]:
pwd

'/content/drive/MyDrive/DEX_Uniswap_Layer2/Poly'

In [3]:
# importing pandas libraries and 
# glob module
import pandas as pd

In [4]:
#@title path
data = "/content/drive/MyDrive/all_pool_uniswap/Poly/January" #@param {type:"string"}

In [5]:
import os

# folder path
dir_path = r'/content/drive/MyDrive/all_pool_uniswap/Poly/January'

# list file and directories
res = os.listdir(dir_path)
print(res)

['uniswap_polygon_2022_01_01.xlsx', 'uniswap_polygon_2022_01_02.xlsx', 'uniswap_polygon_2022_01_03.xlsx', 'uniswap_polygon_2022_01_04.xlsx', 'uniswap_polygon_2022_01_05.xlsx', 'uniswap_polygon_2022_01_06.xlsx', 'uniswap_polygon_2022_01_07.xlsx', 'uniswap_polygon_2022_01_08.xlsx', 'uniswap_polygon_2022_01_09.xlsx', 'uniswap_polygon_2022_01_10.xlsx', 'uniswap_polygon_2022_01_11.xlsx', 'uniswap_polygon_2022_01_12.xlsx', 'uniswap_polygon_2022_01_13.xlsx', 'uniswap_polygon_2022_01_14.xlsx', 'uniswap_polygon_2022_01_15.xlsx', 'uniswap_polygon_2022_01_16.xlsx', 'uniswap_polygon_2022_01_17.xlsx', 'uniswap_polygon_2022_01_18.xlsx', 'uniswap_polygon_2022_01_19.xlsx', 'uniswap_polygon_2022_01_20.xlsx', 'uniswap_polygon_2022_01_21.xlsx', 'uniswap_polygon_2022_01_22.xlsx', 'uniswap_polygon_2022_01_23.xlsx', 'uniswap_polygon_2022_01_24.xlsx', 'uniswap_polygon_2022_01_25.xlsx', 'uniswap_polygon_2022_01_26.xlsx', 'uniswap_polygon_2022_01_27.xlsx', 'uniswap_polygon_2022_01_28.xlsx', 'uniswap_polygon_2022_01_29.xlsx', 'uniswap_polygon_2022_01_30.xlsx', 'uniswap_polygon_2022_01_31.xlsx']

In [6]:
df1 = pd.read_excel(dir_path+"/"+"uniswap_polygon_2022_01_01.xlsx")
df1.head()

,ID,Transaction ID,Timestamp,Timestamp (Unix),Pool,Sender,Recipient,Origin,Token 0 Symbol,Token 1 Symbol,Token 0,Token 1,SqrticeX96,Tick,Log Index,Amount 0 (Excel),Amount 1 (Excel),Amount USD (Excel)
0,0x00001fba73671b143fbea148240d0d468524d71dbcd4...,0x00001fba73671b143fbea148240d0d468524d71dbcd4...,2022-01-01 22:45:37,1641105937,0x8eb315dbd94469016e84098184dd55c1af2edabb,0xe592427a0aece92de3edee1f18e0157c05861564,0xf2e4209afa4c3c9eaa3fb8e12eed25d8f328171c,0x2da9fc8828d3e0c3657379daf511e6e5dec12ac2,XSGD,WETH,0x769434dca303597c8fc4997bf3dab233e961eda2,0x7ceb23fd6bc0add59e62ac25578270cff1b9f619,NaN,191008,277,1.692879,-0.000334,1.247183
1,0x00001fba73671b143fbea148240d0d468524d71dbcd4...,0x00001fba73671b143fbea148240d0d468524d71dbcd4...,2022-01-01 22:45:37,1641105937,0xb2f8ba544e4874d4e0f817359d0f4bcff209b87e,0xe592427a0aece92de3edee1f18e0157c05861564,0xf2e4209afa4c3c9eaa3fb8e12eed25d8f328171c,0x2da9fc8828d3e0c3657379daf511e6e5dec12ac2,USDC,XSGD,0x2791bca1f2de4661ed88a30c99a7a9449aa84174,0x769434dca303597c8fc4997bf3dab233e961eda2,NaN,3038,273,1.250000,-1.692879,1.250000
2,0x00012f97b8d1c8c4a5c1b17e7794115d0edd02968345...,0x00012f97b8d1c8c4a5c1b17e7794115d0edd02968345...,2022-01-01 21:50:51,1641102651,0x0f663c16dd7c65cf87edb9229464ca77aeea536b,0xe592427a0aece92de3edee1f18e0157c05861564,0xdb6f1920a889355780af7570773609bd8cb1f498,0x0a1f2e1a4585bbf5e54a894fffa74133654bfadc,WMATIC,DAI,0x0d500b1d8e8ef31e21c99d1db9a6444d3adf1270,0x8f3cf7ad23cd3cadbd9735aff958023239c6a063,NaN,9261,260,18.000000,-45.426760,45.451973
3,0x000ccef15efc988d77af0dae0002890057a2e9bca2f7...,0x000ccef15efc988d77af0dae0002890057a2e9bca2f7...,2022-01-01 03:30:57,1641036657,0xa374094527e1673a86de625aa59517c5de346d32,0xe592427a0aece92de3edee1f18e0157c05861564,0xdb6f1920a889355780af7570773609bd8cb1f498,0xd072fd519d8e87bd2222c48d2ec5be6fc322b4d6,WMATIC,USDC,0x0d500b1d8e8ef31e21c99d1db9a6444d3adf1270,0x2791bca1f2de4661ed88a30c99a7a9449aa84174,NaN,-267036,79,37.000000,-93.623242,93.700878
4,0x000ef06789b4af2ab513507d0c36581519ef3df2cf09...,0x000ef06789b4af2ab513507d0c36581519ef3df2cf09...,2022-01-01 08:47:29,1641055649,0x45dda9cb7c25131df268515131f647d726f50608,0xe592427a0aece92de3edee1f18e0157c05861564,0xdef171fe48cf0115b1d80b88dc8eab59176fee57,0xff1ebdf738b9bd28c02cd9914f4dd7834dcb41dd,USDC,WETH,0x2791bca1f2de4661ed88a30c99a7a9449aa84174,0x7ceb23fd6bc0add59e62ac25578270cff1b9f619,NaN,194051,366,-1169.026478,0.312736,1168.253282

In [7]:
df1.tail()

,ID,Transaction ID,Timestamp,Timestamp (Unix),Pool,Sender,Recipient,Origin,Token 0 Symbol,Token 1 Symbol,Token 0,Token 1,SqrticeX96,Tick,Log Index,Amount 0 (Excel),Amount 1 (Excel),Amount USD (Excel)
38663,0xfff70ab509903b32c4e07bb4f0e3d75fafc08ddfe88b...,0xfff70ab509903b32c4e07bb4f0e3d75fafc08ddfe88b...,2022-01-01 06:19:06,1641046746,0x0f663c16dd7c65cf87edb9229464ca77aeea536b,0xe592427a0aece92de3edee1f18e0157c05861564,0xdb6f1920a889355780af7570773609bd8cb1f498,0x3dde37369ecbd0065cae286006b14ceb6b379ee1,WMATIC,DAI,0x0d500b1d8e8ef31e21c99d1db9a6444d3adf1270,0x8f3cf7ad23cd3cadbd9735aff958023239c6a063,NaN,9274,374,-0.985270,2.491985,2.492034
38664,0xfffca2424b552d2a1e71793d54b44e8ceadcb8c4a379...,0xfffca2424b552d2a1e71793d54b44e8ceadcb8c4a379...,2022-01-01 12:24:32,1641068672,0x45dda9cb7c25131df268515131f647d726f50608,0xe592427a0aece92de3edee1f18e0157c05861564,0x238e69a96f2336c548cb59a161ed4a9a8ecf9356,0x238e69a96f2336c548cb59a161ed4a9a8ecf9356,USDC,WETH,0x2791bca1f2de4661ed88a30c99a7a9449aa84174,0x7ceb23fd6bc0add59e62ac25578270cff1b9f619,NaN,194030,86,3749.608452,-1.000000,3746.497577
38665,0xfffd4c7a47eb816281fac14df53ea62e6aa865e97d19...,0xfffd4c7a47eb816281fac14df53ea62e6aa865e97d19...,2022-01-01 04:29:43,1641040183,0x45dda9cb7c25131df268515131f647d726f50608,0xe592427a0aece92de3edee1f18e0157c05861564,0xdb6f1920a889355780af7570773609bd8cb1f498,0xff10053ee19eff2925dfd129ed4a460a6f8ee627,USDC,WETH,0x2791bca1f2de4661ed88a30c99a7a9449aa84174,0x7ceb23fd6bc0add59e62ac25578270cff1b9f619,NaN,194154,150,-0.632605,0.000171,0.632467
38666,0xfffd50f81273a8a1166574f7358fec7307e939de7de6...,0xfffd50f81273a8a1166574f7358fec7307e939de7de6...,2022-01-01 11:55:54,1641066954,0x9b08288c3be4f62bbf8d1c20ac9c5e6f9467d8b7,0xe592427a0aece92de3edee1f18e0157c05861564,0xdb6f1920a889355780af7570773609bd8cb1f498,0xc7a894eb2f1c34cb5f1ae88af795fde1ce3dd187,WMATIC,USDT,0x0d500b1d8e8ef31e21c99d1db9a6444d3adf1270,0xc2132d05d31c914a87c6611c10748aeb04b58e8f,NaN,-266868,90,-776.671198,2000.000000,2001.565813
38667,0xfffe8f0bba1ceb6104f9158e1bcefb3bc2e579755aad...,0xfffe8f0bba1ceb6104f9158e1bcefb3bc2e579755aad...,2022-01-01 04:07:28,1641038848,0xbeaf7156ba07c3df8fac42e90188c5a752470db7,0xe592427a0aece92de3edee1f18e0157c05861564,0xdef171fe48cf0115b1d80b88dc8eab59176fee57,0x96929e1c2c075cbee1a8e2d8cead6c08ae2a7ad4,USDC,FRAX,0x2791bca1f2de4661ed88a30c99a7a9449aa84174,0x45c32fa6df82ead1e2ef74d17b76547eddfaff89,NaN,276310,110,57.497754,-57.392157,57.497754

In [8]:
files = res

In [9]:
df =df1
from tqdm import tqdm
for file in tqdm(files): 
    # combining multiple excel worksheets 
    # into single data frames
    df = pd.concat([df, pd.read_excel(dir_path+"/"+file)],
                   ignore_index=True, sort=False)

100%|██████████| 31/31 [07:11<00:00, 13.92s/it]

In [10]:
df_Poly_Jan = df
df_Poly_Jan.tail()

,ID,Transaction ID,Timestamp,Timestamp (Unix),Pool,Sender,Recipient,Origin,Token 0 Symbol,Token 1 Symbol,Token 0,Token 1,SqrticeX96,Tick,Log Index,Amount 0 (Excel),Amount 1 (Excel),Amount USD (Excel)
1518253,0xfff33dd284573f8d92913413cd0a2b5d6e45bcfeeb0a...,0xfff33dd284573f8d92913413cd0a2b5d6e45bcfeeb0a...,2022-01-31 08:17:52,1643645872,0x88f3c15523544835ff6c738ddb30995339ad57d6,0x68b3465833fb72a70ecdf485e0e4c7bd8665fc45,0x8f602a447b3a81c0fb22fa39e2a617540101c8ab,0x8f602a447b3a81c0fb22fa39e2a617540101c8ab,WMATIC,USDC,0x0d500b1d8e8ef31e21c99d1db9a6444d3adf1270,0x2791bca1f2de4661ed88a30c99a7a9449aa84174,NaN,-271485,181,113.920185,-184.284405,184.624014
1518254,0xfff49ecd52c323d1f763c1f76a1bb2170435c43d48e3...,0xfff49ecd52c323d1f763c1f76a1bb2170435c43d48e3...,2022-01-31 23:12:15,1643699535,0x45dda9cb7c25131df268515131f647d726f50608,0xe592427a0aece92de3edee1f18e0157c05861564,0x8b26320912935111300ddaeec15ea9a182ff6f1a,0x8b26320912935111300ddaeec15ea9a182ff6f1a,USDC,WETH,0x2791bca1f2de4661ed88a30c99a7a9449aa84174,0x7ceb23fd6bc0add59e62ac25578270cff1b9f619,NaN,197151,12,8917.551487,-3.249564,8901.906248
1518255,0xfffbb8900e5f3b1e71702191b6a366695cc40e5d13b3...,0xfffbb8900e5f3b1e71702191b6a366695cc40e5d13b3...,2022-01-31 18:32:47,1643682767,0x45dda9cb7c25131df268515131f647d726f50608,0xe592427a0aece92de3edee1f18e0157c05861564,0xf2e4209afa4c3c9eaa3fb8e12eed25d8f328171c,0xe84adc0964ee34ce0319df3418636ed6a4117b97,USDC,WETH,0x2791bca1f2de4661ed88a30c99a7a9449aa84174,0x7ceb23fd6bc0add59e62ac25578270cff1b9f619,NaN,197329,242,-2020.159639,0.750000,2018.008289
1518256,0xfffea687efe694d32d13706d1be8947a85a3f99e5477...,0xfffea687efe694d32d13706d1be8947a85a3f99e5477...,2022-01-31 19:18:47,1643685527,0x3d16492aebb76b40cfa83a64286e74b73a10adaf,0xe592427a0aece92de3edee1f18e0157c05861564,0xdb6f1920a889355780af7570773609bd8cb1f498,0xfa35113163bfd33c18a01d1a62d4d14a1ed30a42,WETH,REQ,0x7ceb23fd6bc0add59e62ac25578270cff1b9f619,0xb25e20de2f2ebb4cffd4d16a55c7b395e8a94762,NaN,93697,232,-7.057228,82100.769231,19217.640325
1518257,0xffffd790fac1d3ee52d5a37089e6f1bfb1f45c184bbe...,0xffffd790fac1d3ee52d5a37089e6f1bfb1f45c184bbe...,2022-01-31 22:23:40,1643696620,0x86f1d8390222a3691c28938ec7404a1661e618e0,0x1111111254fb6c44bac0bed2854e76f90643097d,0x1111111254fb6c44bac0bed2854e76f90643097d,0x7596265415092b8579d10dd7252c5c3b86683f55,WMATIC,WETH,0x0d500b1d8e8ef31e21c99d1db9a6444d3adf1270,0x7ceb23fd6bc0add59e62ac25578270cff1b9f619,NaN,-74184,166,-12.871780,0.007732,21.107504

In [11]:
df_Poly_Jan.to_csv("Poly_Jan.csv")

In [12]:
df_Poly_Jan = pd.read_csv("Poly_Jan.csv")

In [13]:
Poly_Amount_Jan = df_Poly_Jan[["Timestamp", "Amount USD (Excel)"]]

In [14]:
Poly_Amount_Jan.columns =['Timestamp', 'Amount_USD']
Poly_Amount_Jan

                   Timestamp    Amount_USD
0        2022-01-01 22:45:37      1.247183
1        2022-01-01 22:45:37      1.250000
2        2022-01-01 21:50:51     45.451973
3        2022-01-01 03:30:57     93.700878
4        2022-01-01 08:47:29   1168.253282
...                      ...           ...
1518253  2022-01-31 08:17:52    184.624014
1518254  2022-01-31 23:12:15   8901.906248
1518255  2022-01-31 18:32:47   2018.008289
1518256  2022-01-31 19:18:47  19217.640325
1518257  2022-01-31 22:23:40     21.107504

[1518258 rows x 2 columns]

In [15]:
Poly_Amount_Jan['Timestamp']=pd.to_datetime(Poly_Amount_Jan['Timestamp'])
Poly_Amount_Jan.dtypes

<ipython-input-15-1671aa643dd9>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  Poly_Amount_Jan['Timestamp']=pd.to_datetime(Poly_Amount_Jan['Timestamp'])

Timestamp     datetime64[ns]
Amount_USD           float64
dtype: object

In [16]:
Poly_Amount_Jan=Poly_Amount_Jan.sort_values(by='Timestamp')
Poly_Amount_Jan

                  Timestamp   Amount_USD
38944   2022-01-01 00:00:01  1277.224818
276     2022-01-01 00:00:01  1277.224818
57026   2022-01-01 00:00:01  2498.041299
18358   2022-01-01 00:00:01  2498.041299
62578   2022-01-01 00:00:17    51.151019
...                     ...          ...
1511316 2022-01-31 23:59:50    41.312080
1500437 2022-01-31 23:59:52    73.082361
1500438 2022-01-31 23:59:52    73.121584
1482388 2022-01-31 23:59:52    45.035286
1482387 2022-01-31 23:59:52    45.036830

[1518258 rows x 2 columns]

In [17]:
Poly_Amount_Jan.to_csv("Poly_Amount_Jan.csv")