please mount google drive before you begin

# Part I: Set-up and Data Processing

In [2]:
cd /content/drive/MyDrive/DEX_Uniswap_Layer2/Poly

/content/drive/MyDrive/DEX_Uniswap_Layer2/Poly

In [3]:
pwd

'/content/drive/MyDrive/DEX_Uniswap_Layer2/Poly'

In [4]:
# importing pandas libraries and 
# glob module
import pandas as pd

In [5]:
#@title path
data = "/content/drive/MyDrive/all_pool_uniswap/Poly/April" #@param {type:"string"}

In [6]:
import os

# folder path
dir_path = r'/content/drive/MyDrive/all_pool_uniswap/Poly/April'

# list file and directories
res = os.listdir(dir_path)
print(res)

['uniswap_polygon_2022_04_01.xlsx', 'uniswap_polygon_2022_04_02.xlsx', 'uniswap_polygon_2022_04_03.xlsx', 'uniswap_polygon_2022_04_04.xlsx', 'uniswap_polygon_2022_04_05.xlsx', 'uniswap_polygon_2022_04_06.xlsx', 'uniswap_polygon_2022_04_07.xlsx', 'uniswap_polygon_2022_04_08.xlsx', 'uniswap_polygon_2022_04_09.xlsx', 'uniswap_polygon_2022_04_10.xlsx', 'uniswap_polygon_2022_04_12.xlsx', 'uniswap_polygon_2022_04_14.xlsx', 'uniswap_polygon_2022_04_11.xlsx', 'uniswap_polygon_2022_04_13.xlsx', 'uniswap_polygon_2022_04_16.xlsx', 'uniswap_polygon_2022_04_18.xlsx', 'uniswap_polygon_2022_04_15.xlsx', 'uniswap_polygon_2022_04_17.xlsx', 'uniswap_polygon_2022_04_20.xlsx', 'uniswap_polygon_2022_04_22.xlsx', 'uniswap_polygon_2022_04_19.xlsx', 'uniswap_polygon_2022_04_21.xlsx', 'uniswap_polygon_2022_04_23.xlsx', 'uniswap_polygon_2022_04_24.xlsx', 'uniswap_polygon_2022_04_25.xlsx', 'uniswap_polygon_2022_04_28.xlsx', 'uniswap_polygon_2022_04_27.xlsx', 'uniswap_polygon_2022_04_30.xlsx', 'uniswap_polygon_2022_04_29.xlsx', 'uniswap_polygon_2022_04_26.xlsx']

In [7]:
df1 = pd.read_excel(dir_path+"/"+"uniswap_polygon_2022_04_01.xlsx")
df1.head()

,ID,Transaction ID,Timestamp,Timestamp (Unix),Pool,Sender,Recipient,Origin,Token 0 Symbol,Token 1 Symbol,Token 0,Token 1,SqrticeX96,Tick,Log Index,Amount 0 (Excel),Amount 1 (Excel),Amount USD (Excel)
0,0x000093e14e2a2d4600d13cbe12a2d21692c2f1d6075b...,0x000093e14e2a2d4600d13cbe12a2d21692c2f1d6075b...,2022-04-01 03:30:36,1648809036,0x1b40b17d04af7ecf70b553fb3b5e793b8972b414,0xe592427a0aece92de3edee1f18e0157c05861564,0xdb6f1920a889355780af7570773609bd8cb1f498,0x8241655e2dc3bd6596a96ff2e45017bd197e046f,WMATIC,BERYL,0x0d500b1d8e8ef31e21c99d1db9a6444d3adf1270,0xa247b0476c11dab0be132e91fe63b2b7085d7c0e,NaN,63358,138,-3.166092,1803.098952,5.164560
1,0x000140f84bf47ed69e403c1b62f183babb97056cfb0d...,0x000140f84bf47ed69e403c1b62f183babb97056cfb0d...,2022-04-01 18:18:08,1648862288,0x45dda9cb7c25131df268515131f647d726f50608,0xe592427a0aece92de3edee1f18e0157c05861564,0xdef171fe48cf0115b1d80b88dc8eab59176fee57,0x85a82d07fcb71403d0e7cb0611ffb232a2cef969,USDC,WETH,0x2791bca1f2de4661ed88a30c99a7a9449aa84174,0x7ceb23fd6bc0add59e62ac25578270cff1b9f619,NaN,194766,145,6759.684470,-1.940617,6767.580138
2,0x000242d638bf7b87bf230e51e55f321a3d622a533c16...,0x000242d638bf7b87bf230e51e55f321a3d622a533c16...,2022-04-01 15:44:48,1648853088,0xa374094527e1673a86de625aa59517c5de346d32,0x11431a89893025d2a48dca4eddc396f8c8117187,0x11431a89893025d2a48dca4eddc396f8c8117187,0xd3678d44fdd5b0961d8ad11c366a3bc0c1ab8914,WMATIC,USDC,0x0d500b1d8e8ef31e21c99d1db9a6444d3adf1270,0x2791bca1f2de4661ed88a30c99a7a9449aa84174,NaN,-271065,135,-180.676180,305.850605,305.773271
3,0x00025f37403a1d699075a468b8524395cbf34542814f...,0x00025f37403a1d699075a468b8524395cbf34542814f...,2022-04-01 06:37:34,1648820254,0xa374094527e1673a86de625aa59517c5de346d32,0xa0365d77d65c3e08b1ef79153bae066ab82c79d2,0xa0365d77d65c3e08b1ef79153bae066ab82c79d2,0xc517385ee039ae027e3603d6f6a213b664e307ab,WMATIC,USDC,0x0d500b1d8e8ef31e21c99d1db9a6444d3adf1270,0x2791bca1f2de4661ed88a30c99a7a9449aa84174,NaN,-271257,49,-299.991901,498.197085,498.070160
4,0x000439cc91d5015e414703430028bedfca72c1f8e0bd...,0x000439cc91d5015e414703430028bedfca72c1f8e0bd...,2022-04-01 17:30:34,1648859434,0x9b08288c3be4f62bbf8d1c20ac9c5e6f9467d8b7,0xe592427a0aece92de3edee1f18e0157c05861564,0xdef171fe48cf0115b1d80b88dc8eab59176fee57,0xd29f6a37d1c91bd4fe01763b3c268f8ee71a0caa,WMATIC,USDT,0x0d500b1d8e8ef31e21c99d1db9a6444d3adf1270,0xc2132d05d31c914a87c6611c10748aeb04b58e8f,NaN,-271012,136,14.868750,-25.280323,25.287576

In [8]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [9]:
df1.tail()

,ID,Transaction ID,Timestamp,Timestamp (Unix),Pool,Sender,Recipient,Origin,Token 0 Symbol,Token 1 Symbol,Token 0,Token 1,SqrticeX96,Tick,Log Index,Amount 0 (Excel),Amount 1 (Excel),Amount USD (Excel)
64439,0xfffb513ae0e32c17a443fc5c73b1b061b496ffeec391...,0xfffb513ae0e32c17a443fc5c73b1b061b496ffeec391...,2022-04-01 05:18:50,1648815530,0xa374094527e1673a86de625aa59517c5de346d32,0x521709b3cd7f07e29722be0ba28a8ce0e806dbc3,0x521709b3cd7f07e29722be0ba28a8ce0e806dbc3,0xf83941ca6933218810cc8c7e94e8660569fcc41d,WMATIC,USDC,0x0d500b1d8e8ef31e21c99d1db9a6444d3adf1270,0x2791bca1f2de4661ed88a30c99a7a9449aa84174,NaN,-271497,28,-41.098577,66.634067,66.617362
64440,0xfffbc307422dfb7bce991b97067bc88fe49be93451ed...,0xfffbc307422dfb7bce991b97067bc88fe49be93451ed...,2022-04-01 05:32:38,1648816358,0x42f0530351471dab7ec968476d19bd36af9ec52d,0x0bca6d732eaf4e9ae6b9ac53349c6c85087d9d15,0x0bca6d732eaf4e9ae6b9ac53349c6c85087d9d15,0xd76bb1ef246569ae2badf2b4e95dcb0daafa11f8,DAI,USDT,0x8f3cf7ad23cd3cadbd9735aff958023239c6a063,0xc2132d05d31c914a87c6611c10748aeb04b58e8f,NaN,-276329,276,177.712200,-177.535261,177.640823
64441,0xfffbc307422dfb7bce991b97067bc88fe49be93451ed...,0xfffbc307422dfb7bce991b97067bc88fe49be93451ed...,2022-04-01 05:32:38,1648816358,0x9b08288c3be4f62bbf8d1c20ac9c5e6f9467d8b7,0x0bca6d732eaf4e9ae6b9ac53349c6c85087d9d15,0x0bca6d732eaf4e9ae6b9ac53349c6c85087d9d15,0xd76bb1ef246569ae2badf2b4e95dcb0daafa11f8,WMATIC,USDT,0x0d500b1d8e8ef31e21c99d1db9a6444d3adf1270,0xc2132d05d31c914a87c6611c10748aeb04b58e8f,NaN,-271534,279,-109.925357,177.535261,177.807591
64442,0xfffc3a21f2315fcb98bdf37747b7a6eb5399c4320a45...,0xfffc3a21f2315fcb98bdf37747b7a6eb5399c4320a45...,2022-04-01 07:55:01,1648824901,0x67a9fe12fa6082d9d0203c84c6c56d3c4b269f28,0x5c727b35522f6c386ca7564aee799f32ec8a260d,0x885eb7d605143f454b4345aea37ee8bc457ec730,0x2dbf9e23c2c7ba15cacce92b132737f4d9fd3f47,WETH,DAI,0x7ceb23fd6bc0add59e62ac25578270cff1b9f619,0x8f3cf7ad23cd3cadbd9735aff958023239c6a063,NaN,81375,129,0.015550,-53.474740,53.146033
64443,0xfffc3a21f2315fcb98bdf37747b7a6eb5399c4320a45...,0xfffc3a21f2315fcb98bdf37747b7a6eb5399c4320a45...,2022-04-01 07:55:01,1648824901,0x86f1d8390222a3691c28938ec7404a1661e618e0,0x5c727b35522f6c386ca7564aee799f32ec8a260d,0x5c727b35522f6c386ca7564aee799f32ec8a260d,0x2dbf9e23c2c7ba15cacce92b132737f4d9fd3f47,WMATIC,WETH,0x0d500b1d8e8ef31e21c99d1db9a6444d3adf1270,0x7ceb23fd6bc0add59e62ac25578270cff1b9f619,NaN,-76113,137,31.425815,-0.015550,52.885135

In [10]:
files = res

In [11]:
df =df1
from tqdm import tqdm
for file in tqdm(files): 
    # combining multiple excel worksheets 
    # into single data frames
    df = pd.concat([df, pd.read_excel(dir_path+"/"+file)],
                   ignore_index=True, sort=False)

100%|██████████| 30/30 [07:40<00:00, 15.35s/it]

In [12]:
df_Poly_Apr = df
df_Poly_Apr.tail()

,ID,Transaction ID,Timestamp,Timestamp (Unix),Pool,Sender,Recipient,Origin,Token 0 Symbol,Token 1 Symbol,Token 0,Token 1,SqrticeX96,Tick,Log Index,Amount 0 (Excel),Amount 1 (Excel),Amount USD (Excel)
1836765,0xfffa043cdd1570ea6a0afeb9376f19691dc19e1db4d0...,0xfffa043cdd1570ea6a0afeb9376f19691dc19e1db4d0...,2022-04-26 19:33:00,1651026780,0xa9077cdb3d13f45b8b9d87c43e11bce0e73d8631,0xe592427a0aece92de3edee1f18e0157c05861564,0x693fb96fdda3c382fde7f43a622209c3dd028b98,0x693fb96fdda3c382fde7f43a622209c3dd028b98,WMATIC,AAVE,0x0d500b1d8e8ef31e21c99d1db9a6444d3adf1270,0xd6df932a45c0f255f85145f286ea0b292b21c90b,NaN,-49036,32,393.484902,-2.912680,494.636343
1836766,0xfffbf536d49a7c585c8fe95b5a8e7e87d127383e4051...,0xfffbf536d49a7c585c8fe95b5a8e7e87d127383e4051...,2022-04-26 00:06:53,1650956813,0x86f1d8390222a3691c28938ec7404a1661e618e0,0xe592427a0aece92de3edee1f18e0157c05861564,0xe592427a0aece92de3edee1f18e0157c05861564,0xd95f33f9fb2eb7069421482c30100ca84087b21b,WMATIC,WETH,0x0d500b1d8e8ef31e21c99d1db9a6444d3adf1270,0x7ceb23fd6bc0add59e62ac25578270cff1b9f619,NaN,-77187,108,4000.000000,-1.777952,5333.374165
1836767,0xfffbf536d49a7c585c8fe95b5a8e7e87d127383e4051...,0xfffbf536d49a7c585c8fe95b5a8e7e87d127383e4051...,2022-04-26 00:06:53,1650956813,0x45dda9cb7c25131df268515131f647d726f50608,0xe592427a0aece92de3edee1f18e0157c05861564,0x4a55e845d12315765c21c01731a9ce534daef0f7,0xd95f33f9fb2eb7069421482c30100ca84087b21b,USDC,WETH,0x2791bca1f2de4661ed88a30c99a7a9449aa84174,0x7ceb23fd6bc0add59e62ac25578270cff1b9f619,NaN,196313,111,-5301.060519,1.777952,5316.360246
1836768,0xffff2609c511a182d2ea465e868427e050cbf4204b98...,0xffff2609c511a182d2ea465e868427e050cbf4204b98...,2022-04-26 09:24:03,1650990243,0x50eaedb835021e4a108b7290636d62e9765cc6d7,0xe592427a0aece92de3edee1f18e0157c05861564,0x4921aa4f88f82ec172235ee95ed07b96d061e887,0x75e7b00f9a0e0f6a3974f0ae6ba96d9d68326534,WBTC,WETH,0x1bfd67037b42cf73acf2047067bd4f2c47d9bfd6,0x7ceb23fd6bc0add59e62ac25578270cff1b9f619,NaN,256294,56,0.037067,-0.499995,1435.815647
1836769,0xffff2609c511a182d2ea465e868427e050cbf4204b98...,0xffff2609c511a182d2ea465e868427e050cbf4204b98...,2022-04-26 09:24:03,1650990243,0x847b64f9d3a95e977d157866447a5c0a5dfa0ee5,0xe592427a0aece92de3edee1f18e0157c05861564,0xe592427a0aece92de3edee1f18e0157c05861564,0x75e7b00f9a0e0f6a3974f0ae6ba96d9d68326534,WBTC,USDC,0x1bfd67037b42cf73acf2047067bd4f2c47d9bfd6,0x2791bca1f2de4661ed88a30c99a7a9449aa84174,NaN,59589,53,-0.037067,1438.984040,1438.984040

In [13]:
df_Poly_Apr.to_csv("Poly_Apr.csv")

In [14]:
df_Poly_Apr = pd.read_csv("Poly_Apr.csv")

In [15]:
Poly_Amount_Apr = df_Poly_Apr[["Timestamp", "Amount USD (Excel)"]]

In [16]:
Poly_Amount_Apr.columns =['Timestamp', 'Amount_USD']
Poly_Amount_Apr

                   Timestamp   Amount_USD
0        2022-04-01 03:30:36     5.164560
1        2022-04-01 18:18:08  6767.580138
2        2022-04-01 15:44:48   305.773271
3        2022-04-01 06:37:34   498.070160
4        2022-04-01 17:30:34    25.287576
...                      ...          ...
1836765  2022-04-26 19:33:00   494.636343
1836766  2022-04-26 00:06:53  5333.374165
1836767  2022-04-26 00:06:53  5316.360246
1836768  2022-04-26 09:24:03  1435.815647
1836769  2022-04-26 09:24:03  1438.984040

[1836770 rows x 2 columns]

In [17]:
Poly_Amount_Apr['Timestamp']=pd.to_datetime(Poly_Amount_Apr['Timestamp'])
Poly_Amount_Apr.dtypes

<ipython-input-17-0d5db9ee5328>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  Poly_Amount_Apr['Timestamp']=pd.to_datetime(Poly_Amount_Apr['Timestamp'])

Timestamp     datetime64[ns]
Amount_USD           float64
dtype: object

In [18]:
Poly_Amount_Apr=Poly_Amount_Apr.sort_values(by='Timestamp')
Poly_Amount_Apr

                  Timestamp  Amount_USD
63018   2022-04-01 00:00:00    1.618098
127462  2022-04-01 00:00:00    1.618098
127461  2022-04-01 00:00:00    1.618503
63017   2022-04-01 00:00:00    1.618503
127767  2022-04-01 00:00:02   33.540433
...                     ...         ...
1681484 2022-04-30 23:59:58  285.162657
1630728 2022-04-30 23:59:58   26.114930
1630729 2022-04-30 23:59:58  435.421424
1630730 2022-04-30 23:59:58  148.009454
1630344 2022-04-30 23:59:58  133.730175

[1836770 rows x 2 columns]

In [19]:
Poly_Amount_Apr.to_csv("Poly_Amount_Apr.csv")