please mount google drive before you begin

# Part I: Set-up and Data Processing

In [14]:
cd /content/drive/MyDrive/DEX_Uniswap_Layer2/Poly

/content/drive/MyDrive/DEX_Uniswap_Layer2/Poly

In [15]:
pwd

'/content/drive/MyDrive/DEX_Uniswap_Layer2/Poly'

In [16]:
# importing pandas libraries and 
# glob module
import pandas as pd

In [17]:
#@title path
data = "/content/drive/MyDrive/all_pool_uniswap/Poly/Dec2021" #@param {type:"string"}

In [18]:
import os

# folder path
dir_path = r'/content/drive/MyDrive/all_pool_uniswap/Poly/Dec2021'

# list file and directories
res = os.listdir(dir_path)
print(res)

['uniswap_polygon_2021_12_20.xlsx', 'uniswap_polygon_2021_12_21.xlsx', 'uniswap_polygon_2021_12_22.xlsx', 'uniswap_polygon_2021_12_23.xlsx', 'uniswap_polygon_2021_12_24.xlsx', 'uniswap_polygon_2021_12_25.xlsx', 'uniswap_polygon_2021_12_26.xlsx', 'uniswap_polygon_2021_12_27.xlsx', 'uniswap_polygon_2021_12_28.xlsx', 'uniswap_polygon_2021_12_29.xlsx', 'uniswap_polygon_2021_12_30.xlsx', 'uniswap_polygon_2021_12_31.xlsx']

In [7]:
df1 = pd.read_excel(dir_path+"/"+"uniswap_polygon_2021_12_20.xlsx")
df1.head()

,ID,Transaction ID,Timestamp,Timestamp (Unix),Pool,Sender,Recipient,Origin,Token 0 Symbol,Token 1 Symbol,Token 0,Token 1,SqrticeX96,Tick,Log Index,Amount 0 (Excel),Amount 1 (Excel),Amount USD (Excel)
0,0xbd65fdb21240bf51666343f26f7fc97ab2f26865a898...,0xbd65fdb21240bf51666343f26f7fc97ab2f26865a898...,2021-12-20 14:27:40,1640039260,0x0e44ceb592acfc5d3f09d996302eb4c499ff8c10,0x68b3465833fb72a70ecdf485e0e4c7bd8665fc45,0xe866ece4bbd0ac75577225ee2c464ef16dc8b1f3,0xe866ece4bbd0ac75577225ee2c464ef16dc8b1f3,USDC,WETH,0x2791bca1f2de4661ed88a30c99a7a9449aa84174,0x7ceb23fd6bc0add59e62ac25578270cff1b9f619,NaN,193649,325,1,-0.000256,0

In [8]:
df1.tail()

,ID,Transaction ID,Timestamp,Timestamp (Unix),Pool,Sender,Recipient,Origin,Token 0 Symbol,Token 1 Symbol,Token 0,Token 1,SqrticeX96,Tick,Log Index,Amount 0 (Excel),Amount 1 (Excel),Amount USD (Excel)
0,0xbd65fdb21240bf51666343f26f7fc97ab2f26865a898...,0xbd65fdb21240bf51666343f26f7fc97ab2f26865a898...,2021-12-20 14:27:40,1640039260,0x0e44ceb592acfc5d3f09d996302eb4c499ff8c10,0x68b3465833fb72a70ecdf485e0e4c7bd8665fc45,0xe866ece4bbd0ac75577225ee2c464ef16dc8b1f3,0xe866ece4bbd0ac75577225ee2c464ef16dc8b1f3,USDC,WETH,0x2791bca1f2de4661ed88a30c99a7a9449aa84174,0x7ceb23fd6bc0add59e62ac25578270cff1b9f619,NaN,193649,325,1,-0.000256,0

In [19]:
files = res

In [20]:
df =df1
from tqdm import tqdm
for file in tqdm(files): 
    # combining multiple excel worksheets 
    # into single data frames
    df = pd.concat([df, pd.read_excel(dir_path+"/"+file)],
                   ignore_index=True, sort=False)

100%|██████████| 12/12 [02:25<00:00, 12.14s/it]

In [21]:
df_Poly_Dec2021 = df
df_Poly_Dec2021.tail()

,ID,Transaction ID,Timestamp,Timestamp (Unix),Pool,Sender,Recipient,Origin,Token 0 Symbol,Token 1 Symbol,Token 0,Token 1,SqrticeX96,Tick,Log Index,Amount 0 (Excel),Amount 1 (Excel),Amount USD (Excel)
522511,0xfff7ea97ec5c12f32e3aad574ff7f0c95fbbc3b6f475...,0xfff7ea97ec5c12f32e3aad574ff7f0c95fbbc3b6f475...,2021-12-31 09:18:06,1640971086,0x86f1d8390222a3691c28938ec7404a1661e618e0,0xe592427a0aece92de3edee1f18e0157c05861564,0xe592427a0aece92de3edee1f18e0157c05861564,0x93f2316f54bf1d962f007f23c382717ebc4d1762,WMATIC,WETH,0x0d500b1d8e8ef31e21c99d1db9a6444d3adf1270,0x7ceb23fd6bc0add59e62ac25578270cff1b9f619,NaN,-72758,359,98.000000,-0.067816,254.300365
522512,0xfff871cae949cbdfcdbd09e6a8eae64c03d05c093647...,0xfff871cae949cbdfcdbd09e6a8eae64c03d05c093647...,2021-12-31 02:28:39,1640946519,0x9b08288c3be4f62bbf8d1c20ac9c5e6f9467d8b7,0xe592427a0aece92de3edee1f18e0157c05861564,0xdef171fe48cf0115b1d80b88dc8eab59176fee57,0x64d7a7fe703507a4ad8d1860ba5e40673f7ae822,WMATIC,USDT,0x0d500b1d8e8ef31e21c99d1db9a6444d3adf1270,0xc2132d05d31c914a87c6611c10748aeb04b58e8f,NaN,-266742,147,73.000000,-190.219096,190.007620
522513,0xfff87e979ee72bf4850d50b2c3f2f142cb9d51bf5639...,0xfff87e979ee72bf4850d50b2c3f2f142cb9d51bf5639...,2021-12-31 05:16:43,1640956603,0xa374094527e1673a86de625aa59517c5de346d32,0xe592427a0aece92de3edee1f18e0157c05861564,0xdb6f1920a889355780af7570773609bd8cb1f498,0x15177a71af4dde1e190c6a183a8afcf39ae2224a,WMATIC,USDC,0x0d500b1d8e8ef31e21c99d1db9a6444d3adf1270,0x2791bca1f2de4661ed88a30c99a7a9449aa84174,NaN,-266753,42,961.002518,-2501.853483,2500.199783
522514,0xfffae0cf7c1ca19d825bfbebaa6ef6129715b18dd7e1...,0xfffae0cf7c1ca19d825bfbebaa6ef6129715b18dd7e1...,2021-12-31 10:22:36,1640974956,0xa374094527e1673a86de625aa59517c5de346d32,0xe592427a0aece92de3edee1f18e0157c05861564,0xdef171fe48cf0115b1d80b88dc8eab59176fee57,0xbfda7980ca4a45703d49f1fd54d07e8a4bd2ec2f,WMATIC,USDC,0x0d500b1d8e8ef31e21c99d1db9a6444d3adf1270,0x2791bca1f2de4661ed88a30c99a7a9449aa84174,NaN,-266969,191,-210.620162,536.960550,537.583191
522515,0xfffca31e2cc5355cc9603f230568deb5e6c33d2d83dc...,0xfffca31e2cc5355cc9603f230568deb5e6c33d2d83dc...,2021-12-31 04:51:01,1640955061,0x98b9162161164de1ed182a0dfa08f5fbf0f733ca,0xe592427a0aece92de3edee1f18e0157c05861564,0xdb6f1920a889355780af7570773609bd8cb1f498,0x5d0840a6a5ae6a2a1733645dbb61eabb12af78a3,WMATIC,LINK,0x0d500b1d8e8ef31e21c99d1db9a6444d3adf1270,0x53e0bca35ec356bd5dddfebbd1fc0fd03fabad39,NaN,-20586,443,-26.666805,3.413568,69.330211

In [22]:
df_Poly_Dec2021.to_csv("Poly_Dec2021.csv")

In [23]:
df_Poly_Dec2021 = pd.read_csv("Poly_Dec2021.csv")

In [24]:
Poly_Amount_Dec2021 = df_Poly_Dec2021[["Timestamp", "Amount USD (Excel)"]]

In [25]:
Poly_Amount_Dec2021.columns =['Timestamp', 'Amount_USD']
Poly_Amount_Dec2021

                  Timestamp   Amount_USD
0       2021-12-20 14:27:40     0.000000
1       2021-12-20 14:27:40     0.000000
2       2021-12-21 15:37:55    27.498029
3       2021-12-21 19:44:41    12.508844
4       2021-12-21 19:44:41    12.520883
...                     ...          ...
522511  2021-12-31 09:18:06   254.300365
522512  2021-12-31 02:28:39   190.007620
522513  2021-12-31 05:16:43  2500.199783
522514  2021-12-31 10:22:36   537.583191
522515  2021-12-31 04:51:01    69.330211

[522516 rows x 2 columns]

In [26]:
Poly_Amount_Dec2021['Timestamp']=pd.to_datetime(Poly_Amount_Dec2021['Timestamp'])
Poly_Amount_Dec2021.dtypes

<ipython-input-26-9ca977228fcf>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  Poly_Amount_Dec2021['Timestamp']=pd.to_datetime(Poly_Amount_Dec2021['Timestamp'])

Timestamp     datetime64[ns]
Amount_USD           float64
dtype: object

In [27]:
Poly_Amount_Dec2021=Poly_Amount_Dec2021.sort_values(by='Timestamp')
Poly_Amount_Dec2021

                 Timestamp   Amount_USD
0      2021-12-20 14:27:40     0.000000
1      2021-12-20 14:27:40     0.000000
157    2021-12-21 08:20:43    84.811697
156    2021-12-21 08:20:43     0.000000
1001   2021-12-21 08:20:55    10.805575
...                    ...          ...
498620 2021-12-31 23:59:49    15.326698
498621 2021-12-31 23:59:49    15.328350
521997 2021-12-31 23:59:49  2669.878691
512188 2021-12-31 23:59:53   428.609358
513799 2021-12-31 23:59:57    10.043694

[522516 rows x 2 columns]

In [28]:
Poly_Amount_Dec2021.to_csv("Poly_Amount_Dec2021.csv")