please mount google drive before you begin

# Part I: Set-up and Data Processing

In [1]:
cd /content/drive/MyDrive/DEX_Uniswap_Layer2/Eth

/content/drive/MyDrive/DEX_Uniswap_Layer2/Eth

In [2]:
pwd

'/content/drive/MyDrive/DEX_Uniswap_Layer2/Eth'

In [3]:
# importing pandas libraries and 
# glob module
import pandas as pd

In [4]:
#@title path
data = "/content/drive/MyDrive/all_pool_uniswap/Eth/2022/May" #@param {type:"string"}

In [5]:
import os

# folder path
dir_path = r'/content/drive/MyDrive/all_pool_uniswap/Eth/2022/May'

# list file and directories
res = os.listdir(dir_path)
print(res)

['uniswap_ethereum_2022_05_01.xlsx', 'uniswap_ethereum_2022_05_02.xlsx', 'uniswap_ethereum_2022_05_03.xlsx', 'uniswap_ethereum_2022_05_04.xlsx', 'uniswap_ethereum_2022_05_05.xlsx', 'uniswap_ethereum_2022_05_06.xlsx', 'uniswap_ethereum_2022_05_07.xlsx', 'uniswap_ethereum_2022_05_08.xlsx', 'uniswap_ethereum_2022_05_09.xlsx', 'uniswap_ethereum_2022_05_10.xlsx', 'uniswap_ethereum_2022_05_11.xlsx', 'uniswap_ethereum_2022_05_12.xlsx', 'uniswap_ethereum_2022_05_13.xlsx', 'uniswap_ethereum_2022_05_14.xlsx', 'uniswap_ethereum_2022_05_15.xlsx', 'uniswap_ethereum_2022_05_16.xlsx', 'uniswap_ethereum_2022_05_17.xlsx', 'uniswap_ethereum_2022_05_18.xlsx', 'uniswap_ethereum_2022_05_19.xlsx', 'uniswap_ethereum_2022_05_20.xlsx', 'uniswap_ethereum_2022_05_21.xlsx', 'uniswap_ethereum_2022_05_22.xlsx', 'uniswap_ethereum_2022_05_23.xlsx', 'uniswap_ethereum_2022_05_24.xlsx', 'uniswap_ethereum_2022_05_25.xlsx', 'uniswap_ethereum_2022_05_26.xlsx', 'uniswap_ethereum_2022_05_27.xlsx', 'uniswap_ethereum_2022_05_28.xlsx', 'uniswap_ethereum_2022_05_29.xlsx', 'uniswap_ethereum_2022_05_30.xlsx', 'uniswap_ethereum_2022_05_31.xlsx']

In [6]:
df1 = pd.read_excel(dir_path+"/"+"uniswap_ethereum_2022_05_01.xlsx")
df1.head()

,ID,Transaction ID,Timestamp,Timestamp (Unix),Pool,Sender,Recipient,Origin,Token 0 Symbol,Token 1 Symbol,Token 0,Token 1,SqrticeX96,Tick,Log Index,Amount 0 (Excel),Amount 1 (Excel),Amount USD (Excel)
0,0x00008c10c79798fce49986330474b8dddc284da106d6...,0x00008c10c79798fce49986330474b8dddc284da106d6...,2022-05-01 02:46:05,1651398365,0x82c427adfdf2d245ec51d8046b41c4ee87f0d29c,0xe592427a0aece92de3edee1f18e0157c05861564,0xe592427a0aece92de3edee1f18e0157c05861564,0xc2077c37db4081a65e97edc4ed96717162e37163,WETH,oSQTH,0xc02aaa39b223fe8d0a0e5c4f27ead9083c756cc2,0xf1b99e3e573a1a9c5e6b2ce818b617f0e664e86b,NaN,15893,19,-0.049700,0.244264,137.358216
1,0x00008db1739018f185deba6144052cd7bbbc6be4250c...,0x00008db1739018f185deba6144052cd7bbbc6be4250c...,2022-05-01 10:50:05,1651427405,0x4c54ff7f1c424ff5487a32aad0b48b19cbaf087f,0x27239549dd40e1d60f5b80b0c4196923745b1fd2,0x27239549dd40e1d60f5b80b0c4196923745b1fd2,0xb9368b8ec3ce8c4fa20774ffb985db6e4bee22df,NEXO,WETH,0xb62132e35a6c13ee1ee0f84dc5d40bad8d815206,0xc02aaa39b223fe8d0a0e5c4f27ead9083c756cc2,NaN,-70984,258,2600.000000,-2.143722,6025.104537
2,0x0007e203725dd745d7b8f187bb7579022d7a90121e72...,0x0007e203725dd745d7b8f187bb7579022d7a90121e72...,2022-05-01 15:54:19,1651445659,0x70bb8e6844dfb681810fd557dd741bcaf027bf94,0x00000000003b3cc22af3ae1eac0440bcee416b40,0x72ea6ca0d47b337f1ea44314d9d90e2a897edaf5,0xb58555fcba6479fced7de1485eb054943a09af7b,OGN,WETH,0x8207c1ffc5b6804f6024322ccf34f29c3541ae26,0xc02aaa39b223fe8d0a0e5c4f27ead9083c756cc2,NaN,-87602,16,-57139.989916,8.930982,25028.618804
3,0x000880e3e7934f0552bf54190cdb0be02cec4975e83e...,0x000880e3e7934f0552bf54190cdb0be02cec4975e83e...,2022-05-01 02:26:48,1651397208,0xac4b3dacb91461209ae9d41ec517c2b9cb1b7daf,0x68b3465833fb72a70ecdf485e0e4c7bd8665fc45,0x68b3465833fb72a70ecdf485e0e4c7bd8665fc45,0x052dfb0cb1c8dc0b08f7373505ea9a3163760600,APE,WETH,0x4d224452801aced8b2f0aebe155379bb5d594381,0xc02aaa39b223fe8d0a0e5c4f27ead9083c756cc2,NaN,-50688,199,309.000000,-1.938425,5376.546727
4,0x00097038c564afce799a44aff67041f8f98d194047c4...,0x00097038c564afce799a44aff67041f8f98d194047c4...,2022-05-01 05:15:38,1651407338,0x88e6a0c2ddd26feeb64f039a2c41296fcb3f5640,0x68b3465833fb72a70ecdf485e0e4c7bd8665fc45,0xab97237a31f85ce38ce71be394513de7ec6e7b5e,0xab97237a31f85ce38ce71be394513de7ec6e7b5e,USDC,WETH,0xa0b86991c6218b36c1d19d4a2e9eb0ce3606eb48,0xc02aaa39b223fe8d0a0e5c4f27ead9083c756cc2,NaN,197096,123,-39977.077561,14.500000,40014.134489

In [7]:
df1.tail()

,ID,Transaction ID,Timestamp,Timestamp (Unix),Pool,Sender,Recipient,Origin,Token 0 Symbol,Token 1 Symbol,Token 0,Token 1,SqrticeX96,Tick,Log Index,Amount 0 (Excel),Amount 1 (Excel),Amount USD (Excel)
33207,0xfffb155e54b4c96bf098d697deae4f30b79a7365e47f...,0xfffb155e54b4c96bf098d697deae4f30b79a7365e47f...,2022-05-01 01:07:03,1651392423,0xac4b3dacb91461209ae9d41ec517c2b9cb1b7daf,0x68b3465833fb72a70ecdf485e0e4c7bd8665fc45,0x7c76a64ac61d1eeafe2b8af6f7f0a6a1890418f3,0x7c76a64ac61d1eeafe2b8af6f7f0a6a1890418f3,APE,WETH,0x4d224452801aced8b2f0aebe155379bb5d594381,0xc02aaa39b223fe8d0a0e5c4f27ead9083c756cc2,NaN,-50532,293,-478.237521,3.065140,8485.303114
33208,0xfffb155e54b4c96bf098d697deae4f30b79a7365e47f...,0xfffb155e54b4c96bf098d697deae4f30b79a7365e47f...,2022-05-01 01:07:03,1651392423,0x88e6a0c2ddd26feeb64f039a2c41296fcb3f5640,0x68b3465833fb72a70ecdf485e0e4c7bd8665fc45,0x68b3465833fb72a70ecdf485e0e4c7bd8665fc45,0x7c76a64ac61d1eeafe2b8af6f7f0a6a1890418f3,USDC,WETH,0xa0b86991c6218b36c1d19d4a2e9eb0ce3606eb48,0xc02aaa39b223fe8d0a0e5c4f27ead9083c756cc2,NaN,197047,290,8500.000000,-3.065140,8492.651557
33209,0xfffd02b51b1840e792d58b94926069162895ffdb0b81...,0xfffd02b51b1840e792d58b94926069162895ffdb0b81...,2022-05-01 02:25:36,1651397136,0xac4b3dacb91461209ae9d41ec517c2b9cb1b7daf,0x68b3465833fb72a70ecdf485e0e4c7bd8665fc45,0x68b3465833fb72a70ecdf485e0e4c7bd8665fc45,0x93dc57f81ba42b74795a9ec050460813ab02097d,APE,WETH,0x4d224452801aced8b2f0aebe155379bb5d594381,0xc02aaa39b223fe8d0a0e5c4f27ead9083c756cc2,NaN,-50709,312,685.102755,-4.288999,11896.261819
33210,0xfffd02b51b1840e792d58b94926069162895ffdb0b81...,0xfffd02b51b1840e792d58b94926069162895ffdb0b81...,2022-05-01 02:25:36,1651397136,0x11b815efb8f581194ae79006d24e0d814b7697f6,0x68b3465833fb72a70ecdf485e0e4c7bd8665fc45,0x93dc57f81ba42b74795a9ec050460813ab02097d,0x93dc57f81ba42b74795a9ec050460813ab02097d,WETH,USDT,0xc02aaa39b223fe8d0a0e5c4f27ead9083c756cc2,0xdac17f958d2ee523a2206206994597c13d831ec7,NaN,-197060,315,4.288999,-11868.911121,11882.586470
33211,0xfffee21b3a89ee130a6d309ccf2bdaaac26c67dd93a2...,0xfffee21b3a89ee130a6d309ccf2bdaaac26c67dd93a2...,2022-05-01 04:51:29,1651405889,0x92560c178ce069cc014138ed3c2f5221ba71f58a,0xdef1c0ded9bec7f1a1670819833240f027b25eff,0xdef1c0ded9bec7f1a1670819833240f027b25eff,0x47f63066f2d07c3740ab3bcf07071674f707b70d,WETH,ENS,0xc02aaa39b223fe8d0a0e5c4f27ead9083c756cc2,0xc18360217d8f7ab5e7c516566761ea12ce7f9d72,NaN,49932,148,-0.270629,40.000000,748.033110

In [8]:
files = res

In [ ]:
df =df1
from tqdm import tqdm
for file in tqdm(files): 
    # combining multiple excel worksheets 
    # into single data frames
    df = pd.concat([df, pd.read_excel(dir_path+"/"+file)],
                   ignore_index=True, sort=False)

 55%|█████▍    | 17/31 [03:19<02:50, 12.20s/it]

In [ ]:
df_Eth_May = df
df_Eth_May.tail()

In [ ]:
df_Eth_May.to_csv("Eth_May.csv")

In [ ]:
df_Eth_May = pd.read_csv("Eth_May.csv")

In [13]:
Eth_Amount_May = df_Eth_May[["Timestamp", "Amount USD (Excel)"]]

In [14]:
Eth_Amount_May.columns =['Timestamp', 'Amount_USD']
Eth_Amount_May

                   Timestamp    Amount_USD
0        2022-05-01 02:46:05    137.358216
1        2022-05-01 10:50:05   6025.104537
2        2022-05-01 15:54:19  25028.618804
3        2022-05-01 02:26:48   5376.546727
4        2022-05-01 05:15:38  40014.134489
...                      ...           ...
1194931  2022-05-31 06:51:20    387.935033
1194932  2022-05-31 14:37:24  85198.917920
1194933  2022-05-31 13:14:48   4982.708632
1194934  2022-05-31 05:24:03  34236.579949
1194935  2022-05-31 05:16:47     48.962767

[1194936 rows x 2 columns]

In [15]:
Eth_Amount_May['Timestamp']=pd.to_datetime(Eth_Amount_May['Timestamp'])
Eth_Amount_May.dtypes

<ipython-input-15-2d25aec60bdb>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  Eth_Amount_May['Timestamp']=pd.to_datetime(Eth_Amount_May['Timestamp'])

Timestamp     datetime64[ns]
Amount_USD           float64
dtype: object

In [16]:
Eth_Amount_May=Eth_Amount_May.sort_values(by='Timestamp')
Eth_Amount_May

                  Timestamp     Amount_USD
10328   2022-05-01 00:00:06    2940.298316
54298   2022-05-01 00:00:06    6533.476402
65252   2022-05-01 00:00:06   11318.893423
25432   2022-05-01 00:00:06   10962.139524
39723   2022-05-01 00:00:06  104090.787691
...                     ...            ...
1186916 2022-05-31 23:59:57     103.843989
1176974 2022-05-31 23:59:57    8173.118571
1186667 2022-05-31 23:59:57    1327.129278
1193537 2022-05-31 23:59:57    1024.005822
1176973 2022-05-31 23:59:57    8121.242521

[1194936 rows x 2 columns]

In [17]:
Eth_Amount_May.to_csv("Eth_Amount_May.csv")