please mount google drive before you begin

# Part I: Set-up and Data Processing

In [1]:
cd /content/drive/MyDrive/DEX_Uniswap_Layer2/Eth

/content/drive/MyDrive/DEX_Uniswap_Layer2/Eth

In [2]:
pwd

'/content/drive/MyDrive/DEX_Uniswap_Layer2/Eth'

In [3]:
# importing pandas libraries and 
# glob module
import pandas as pd

In [4]:
#@title path
data = "/content/drive/MyDrive/all_pool_uniswap/Eth/2022/March" #@param {type:"string"}

In [5]:
import os

# folder path
dir_path = r'/content/drive/MyDrive/all_pool_uniswap/Eth/2022/March'

# list file and directories
res = os.listdir(dir_path)
print(res)

['uniswap_ethereum_2022_03_01.xlsx', 'uniswap_ethereum_2022_03_02.xlsx', 'uniswap_ethereum_2022_03_03.xlsx', 'uniswap_ethereum_2022_03_04.xlsx', 'uniswap_ethereum_2022_03_05.xlsx', 'uniswap_ethereum_2022_03_06.xlsx', 'uniswap_ethereum_2022_03_07.xlsx', 'uniswap_ethereum_2022_03_08.xlsx', 'uniswap_ethereum_2022_03_09.xlsx', 'uniswap_ethereum_2022_30_10.xlsx', 'uniswap_ethereum_2022_03_11.xlsx', 'uniswap_ethereum_2022_03_12.xlsx', 'uniswap_ethereum_2022_03_13.xlsx', 'uniswap_ethereum_2022_03_14.xlsx', 'uniswap_ethereum_2022_03_15.xlsx', 'uniswap_ethereum_2022_03_16.xlsx', 'uniswap_ethereum_2022_03_17.xlsx', 'uniswap_ethereum_2022_03_18.xlsx', 'uniswap_ethereum_2022_03_19.xlsx', 'uniswap_ethereum_2022_03_20.xlsx', 'uniswap_ethereum_2022_03_21.xlsx', 'uniswap_ethereum_2022_03_22.xlsx', 'uniswap_ethereum_2022_03_23.xlsx', 'uniswap_ethereum_2022_03_24.xlsx', 'uniswap_ethereum_2022_03_25.xlsx', 'uniswap_ethereum_2022_03_26.xlsx', 'uniswap_ethereum_2022_03_27.xlsx', 'uniswap_ethereum_2022_03_28.xlsx', 'uniswap_ethereum_2022_03_29.xlsx', 'uniswap_ethereum_2022_03_30.xlsx', 'uniswap_ethereum_2022_03_31.xlsx']

In [6]:
df1 = pd.read_excel(dir_path+"/"+"uniswap_ethereum_2022_03_01.xlsx")
df1.head()

,ID,Transaction ID,Timestamp,Timestamp (Unix),Pool,Sender,Recipient,Origin,Token 0 Symbol,Token 1 Symbol,Token 0,Token 1,SqrticeX96,Tick,Log Index,Amount 0 (Excel),Amount 1 (Excel),Amount USD (Excel)
0,0x0000674453708177cf4be57ce0bd9e69ae3f3b44150f...,0x0000674453708177cf4be57ce0bd9e69ae3f3b44150f...,2022-03-01 01:52:06,1646128326,0x88e6a0c2ddd26feeb64f039a2c41296fcb3f5640,0x68b3465833fb72a70ecdf485e0e4c7bd8665fc45,0x1d9d70dfb62b41f1ff8f7c3efa60df23c316fb7a,0x1d9d70dfb62b41f1ff8f7c3efa60df23c316fb7a,USDC,WETH,0xa0b86991c6218b36c1d19d4a2e9eb0ce3606eb48,0xc02aaa39b223fe8d0a0e5c4f27ead9083c756cc2,NaN,196601,297,-5961.973216,2.058230,5963.258559
1,0x0000674453708177cf4be57ce0bd9e69ae3f3b44150f...,0x0000674453708177cf4be57ce0bd9e69ae3f3b44150f...,2022-03-01 01:52:06,1646128326,0xefbd546647fda46067225bd0221e08ba91071584,0x68b3465833fb72a70ecdf485e0e4c7bd8665fc45,0x68b3465833fb72a70ecdf485e0e4c7bd8665fc45,0x1d9d70dfb62b41f1ff8f7c3efa60df23c316fb7a,RVP,WETH,0x17ef75aa22dd5f6c2763b8304ab24f40ee54d48a,0xc02aaa39b223fe8d0a0e5c4f27ead9083c756cc2,NaN,-116716,294,235875.379747,-2.058230,5964.543902
2,0x00069b40a915024869f21fdf401c0d713ee12f23a20a...,0x00069b40a915024869f21fdf401c0d713ee12f23a20a...,2022-03-01 03:19:28,1646133568,0x9e0905249ceefffb9605e034b534544684a58be6,0x68b3465833fb72a70ecdf485e0e4c7bd8665fc45,0x68b3465833fb72a70ecdf485e0e4c7bd8665fc45,0x329f6c1968b3dd8f09e0b8098ae4281a6c9b425e,HEX,WETH,0x2b591e99afe9f32eaa6214f7b7629768c40eeb39,0xc02aaa39b223fe8d0a0e5c4f27ead9083c756cc2,NaN,130835,255,2500.000000,-0.119805,348.912893
3,0x000d9541be733b1010cdc66e85949ea47490e2819087...,0x000d9541be733b1010cdc66e85949ea47490e2819087...,2022-03-01 20:36:47,1646195807,0x11b815efb8f581194ae79006d24e0d814b7697f6,0x8aff5ca996f77487a4f04f1ce905bf3d27455580,0x8aff5ca996f77487a4f04f1ce905bf3d27455580,0xb0305e86b143fe018663a5ce6a3781ffccecb719,WETH,USDT,0xc02aaa39b223fe8d0a0e5c4f27ead9083c756cc2,0xdac17f958d2ee523a2206206994597c13d831ec7,NaN,-196172,2,70.500924,-213398.817765,213266.144034
4,0x0010c9b6ab8fed2f8cfa34a1fba05860e5d7adfb73be...,0x0010c9b6ab8fed2f8cfa34a1fba05860e5d7adfb73be...,2022-03-01 14:04:54,1646172294,0xd34e4855146ac0c6d0e4a652bd5fb54830f91ba8,0xdef1c0ded9bec7f1a1670819833240f027b25eff,0xdef1c0ded9bec7f1a1670819833240f027b25eff,0xb296cea894ba0a5d0f67ec671d9525985e15a616,STRONG,WETH,0x990f341946a3fdb507ae7e52d17851b87168017c,0xc02aaa39b223fe8d0a0e5c4f27ead9083c756cc2,NaN,-24474,193,46.000000,-3.978967,11739.626533

In [7]:
df1.tail()

,ID,Transaction ID,Timestamp,Timestamp (Unix),Pool,Sender,Recipient,Origin,Token 0 Symbol,Token 1 Symbol,Token 0,Token 1,SqrticeX96,Tick,Log Index,Amount 0 (Excel),Amount 1 (Excel),Amount USD (Excel)
36470,0xfffd0300f0e615bf5a68a30d104ae3e1d32dd9943fcd...,0xfffd0300f0e615bf5a68a30d104ae3e1d32dd9943fcd...,2022-03-01 14:17:22,1646173042,0x11b815efb8f581194ae79006d24e0d814b7697f6,0x68b3465833fb72a70ecdf485e0e4c7bd8665fc45,0x68b3465833fb72a70ecdf485e0e4c7bd8665fc45,0x35ec348ee9a8b8e7a4490d7c0e6ba9bb75eb466e,WETH,USDT,0xc02aaa39b223fe8d0a0e5c4f27ead9083c756cc2,0xdac17f958d2ee523a2206206994597c13d831ec7,NaN,-196423,292,-1.810163,5343.410000,5342.076608
36471,0xfffda35f13ecc1d97ff68a319f6fc12a88397ad28105...,0xfffda35f13ecc1d97ff68a319f6fc12a88397ad28105...,2022-03-01 09:54:37,1646157277,0x4b5ab61593a2401b1075b90c04cbcdd3f87ce011,0xbf5a94acc740a485ecc45b8407af0fe40a87cef5,0x8817d887960737a604cf712d3e5da8673dddb7f0,0x8817d887960737a604cf712d3e5da8673dddb7f0,WETH,LOOKS,0xc02aaa39b223fe8d0a0e5c4f27ead9083c756cc2,0xf4d2888d29d722226fafa5d9b24f9164c092421e,NaN,76880,81,-13.725899,29996.250469,40444.977621
36472,0xfffdc50969bed38870f73ab44d77c4d6c7b2d75a9649...,0xfffdc50969bed38870f73ab44d77c4d6c7b2d75a9649...,2022-03-01 09:56:56,1646157416,0x11b815efb8f581194ae79006d24e0d814b7697f6,0x68b3465833fb72a70ecdf485e0e4c7bd8665fc45,0x0c9ac5677ecc83cdad0afb129abfd80ff4cf1dcb,0x0c9ac5677ecc83cdad0afb129abfd80ff4cf1dcb,WETH,USDT,0xc02aaa39b223fe8d0a0e5c4f27ead9083c756cc2,0xdac17f958d2ee523a2206206994597c13d831ec7,NaN,-196487,195,0.125000,-366.292190,366.947400
36473,0xfffe9b6a44c8c6646f5383037b19f83455fe4600ea29...,0xfffe9b6a44c8c6646f5383037b19f83455fe4600ea29...,2022-03-01 16:41:45,1646181705,0xb404057ee4b1d7359ca5a57ac1c020b74c23e56b,0xe592427a0aece92de3edee1f18e0157c05861564,0x0f4ee9631f4be0a63756515141281a3e2b293bbe,0x0f4ee9631f4be0a63756515141281a3e2b293bbe,FTX Token,WETH,0x50d1c9771902476076ecfc8b2a83ad6b9355a4c9,0xc02aaa39b223fe8d0a0e5c4f27ead9083c756cc2,NaN,-41628,18,-260.015021,4.056680,11899.736788
36474,0xffff7aa8049c9f51de9ca2d7e676fe0c615c1c5506cb...,0xffff7aa8049c9f51de9ca2d7e676fe0c615c1c5506cb...,2022-03-01 22:49:38,1646203778,0x88e6a0c2ddd26feeb64f039a2c41296fcb3f5640,0x4cb18386e5d1f34dc6eea834bf3534a970a3f8e7,0x56178a0d5f301baf6cf3e1cd53d9863437345bf9,0x042523db4f3effc33d2742022b2490258494f8b3,USDC,WETH,0xa0b86991c6218b36c1d19d4a2e9eb0ce3606eb48,0xc02aaa39b223fe8d0a0e5c4f27ead9083c756cc2,NaN,196347,5,604.854240,-0.203354,605.304312

In [8]:
files = res

In [9]:
df =df1
from tqdm import tqdm
for file in tqdm(files): 
    # combining multiple excel worksheets 
    # into single data frames
    df = pd.concat([df, pd.read_excel(dir_path+"/"+file)],
                   ignore_index=True, sort=False)

100%|██████████| 31/31 [05:28<00:00, 10.59s/it]

In [10]:
df_Eth_Mar = df
df_Eth_Mar.tail()

,ID,Transaction ID,Timestamp,Timestamp (Unix),Pool,Sender,Recipient,Origin,Token 0 Symbol,Token 1 Symbol,Token 0,Token 1,SqrticeX96,Tick,Log Index,Amount 0 (Excel),Amount 1 (Excel),Amount USD (Excel)
1194266,0xfff678a505050925cbe1559a3d8964094c456a940833...,0xfff678a505050925cbe1559a3d8964094c456a940833...,2022-03-31 15:21:42,1648765302,0x4e68ccd3e89f51c3074ca5072bbac773960dfa36,0x68b3465833fb72a70ecdf485e0e4c7bd8665fc45,0x68b3465833fb72a70ecdf485e0e4c7bd8665fc45,0x1ae330acac71a2209893bb19d970f8ca9a6e0fb5,WETH,USDT,0xc02aaa39b223fe8d0a0e5c4f27ead9083c756cc2,0xdac17f958d2ee523a2206206994597c13d831ec7,NaN,-195351,23,2.160000,-7072.957500,7083.746106
1194267,0xfff678a505050925cbe1559a3d8964094c456a940833...,0xfff678a505050925cbe1559a3d8964094c456a940833...,2022-03-31 15:21:42,1648765302,0x19f83460e387f1b01f94b85c2532ebc15b0b712e,0x68b3465833fb72a70ecdf485e0e4c7bd8665fc45,0x1ae330acac71a2209893bb19d970f8ca9a6e0fb5,0x1ae330acac71a2209893bb19d970f8ca9a6e0fb5,USDT,SAITO,0xdac17f958d2ee523a2206206994597c13d831ec7,0xfa14fa6958401314851a17d6c5360ca29f74b57b,NaN,308451,26,7072.957500,-175972.412231,7072.957500
1194268,0xfffba4aceb7ac57c9896cbeb1bd53b7d8b9d66657f6e...,0xfffba4aceb7ac57c9896cbeb1bd53b7d8b9d66657f6e...,2022-03-31 12:29:56,1648754996,0x1c98562a2fab5af19d8fb3291a36ac3c618835d9,0x68b3465833fb72a70ecdf485e0e4c7bd8665fc45,0x68b3465833fb72a70ecdf485e0e4c7bd8665fc45,0xded5cef8f83b609749ed82ac43549f8128f87d5b,Metis,WETH,0x9e32b13ce7f2e80a01932b42553652e053d6ed8e,0xc02aaa39b223fe8d0a0e5c4f27ead9083c756cc2,NaN,-31953,10,23.251190,-0.949794,3133.564220
1194269,0xfffc0ff702f1f12d56b7aba5d1f2d4056784b80e9a8c...,0xfffc0ff702f1f12d56b7aba5d1f2d4056784b80e9a8c...,2022-03-31 21:33:49,1648787629,0xd0effc6828972483db1c64106f71d6ad12606a53,0xe592427a0aece92de3edee1f18e0157c05861564,0xe592427a0aece92de3edee1f18e0157c05861564,0x930c4667464fc346b4065b3ffde8d4a8533c0ed3,DAI,MTA,0x6b175474e89094c44da98b954eedeac495271d0f,0xa3bed4e1c75d00fa6f4e5e6922db7261b5e9acd2,NaN,8665,220,-262.542777,625.476374,262.542777
1194270,0xfffc0ff702f1f12d56b7aba5d1f2d4056784b80e9a8c...,0xfffc0ff702f1f12d56b7aba5d1f2d4056784b80e9a8c...,2022-03-31 21:33:49,1648787629,0x6c6bc977e13df9b0de53b251522280bb72383700,0xe592427a0aece92de3edee1f18e0157c05861564,0x930c4667464fc346b4065b3ffde8d4a8533c0ed3,0x930c4667464fc346b4065b3ffde8d4a8533c0ed3,DAI,USDC,0x6b175474e89094c44da98b954eedeac495271d0f,0xa0b86991c6218b36c1d19d4a2e9eb0ce3606eb48,NaN,-276326,223,262.542777,-262.379489,262.461133

In [11]:
df_Eth_Mar.to_csv("Eth_Mar.csv")

In [12]:
df_Eth_Mar = pd.read_csv("Eth_Mar.csv")

In [13]:
Eth_Amount_Mar = df_Eth_Mar[["Timestamp", "Amount USD (Excel)"]]

In [14]:
Eth_Amount_Mar.columns =['Timestamp', 'Amount_USD']
Eth_Amount_Mar

                   Timestamp     Amount_USD
0        2022-03-01 01:52:06    5963.258559
1        2022-03-01 01:52:06    5964.543902
2        2022-03-01 03:19:28     348.912893
3        2022-03-01 20:36:47  213266.144034
4        2022-03-01 14:04:54   11739.626533
...                      ...            ...
1194266  2022-03-31 15:21:42    7083.746106
1194267  2022-03-31 15:21:42    7072.957500
1194268  2022-03-31 12:29:56    3133.564220
1194269  2022-03-31 21:33:49     262.542777
1194270  2022-03-31 21:33:49     262.461133

[1194271 rows x 2 columns]

In [15]:
Eth_Amount_Mar['Timestamp']=pd.to_datetime(Eth_Amount_Mar['Timestamp'])
Eth_Amount_Mar.dtypes

<ipython-input-15-19e711c60318>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  Eth_Amount_Mar['Timestamp']=pd.to_datetime(Eth_Amount_Mar['Timestamp'])

Timestamp     datetime64[ns]
Amount_USD           float64
dtype: object

In [16]:
Eth_Amount_Mar=Eth_Amount_Mar.sort_values(by='Timestamp')
Eth_Amount_Mar

                  Timestamp    Amount_USD
51379   2022-03-01 00:00:10   6380.439001
71435   2022-03-01 00:00:10    290.986681
13548   2022-03-01 00:00:10   2921.335970
34960   2022-03-01 00:00:10    290.986681
56753   2022-03-01 00:00:10   7675.318811
...                     ...           ...
1182151 2022-03-31 23:59:49      0.000000
1182152 2022-03-31 23:59:49  10270.625862
1178736 2022-03-31 23:59:49    356.259343
1160717 2022-03-31 23:59:49  11189.749386
1160487 2022-03-31 23:59:52   1144.090980

[1194271 rows x 2 columns]

In [17]:
Eth_Amount_Mar.to_csv("Eth_Amount_Mar.csv")