please mount google drive before you begin

# Part I: Set-up and Data Processing

In [22]:
cd /content/drive/MyDrive/DEX_Uniswap_Layer2/Eth

/content/drive/MyDrive/DEX_Uniswap_Layer2/Eth

In [8]:
pwd

'/content/drive/MyDrive/DEX_Uniswap_Layer2/Eth'

In [9]:
# importing pandas libraries and 
# glob module
import pandas as pd

In [4]:
#@title path
data = "/content/drive/MyDrive/all_pool_uniswap/Eth/2022/February" #@param {type:"string"}

In [6]:
import os

# folder path
dir_path = r'/content/drive/MyDrive/all_pool_uniswap/Eth/2022/February'

# list file and directories
res = os.listdir(dir_path)
print(res)

['uniswap_ethereum_2022_02_01.xlsx', 'uniswap_ethereum_2022_02_02.xlsx', 'uniswap_ethereum_2022_02_03.xlsx', 'uniswap_ethereum_2022_02_04.xlsx', 'uniswap_ethereum_2022_02_05.xlsx', 'uniswap_ethereum_2022_02_06.xlsx', 'uniswap_ethereum_2022_02_07.xlsx', 'uniswap_ethereum_2022_02_08.xlsx', 'uniswap_ethereum_2022_02_09.xlsx', 'uniswap_ethereum_2022_02_10.xlsx', 'uniswap_ethereum_2022_02_11.xlsx', 'uniswap_ethereum_2022_02_12.xlsx', 'uniswap_ethereum_2022_02_13.xlsx', 'uniswap_ethereum_2022_02_14.xlsx', 'uniswap_ethereum_2022_02_15.xlsx', 'uniswap_ethereum_2022_02_16.xlsx', 'uniswap_ethereum_2022_02_17.xlsx', 'uniswap_ethereum_2022_02_18.xlsx', 'uniswap_ethereum_2022_02_19.xlsx', 'uniswap_ethereum_2022_02_20.xlsx', 'uniswap_ethereum_2022_02_21.xlsx', 'uniswap_ethereum_2022_02_22.xlsx', 'uniswap_ethereum_2022_02_23.xlsx', 'uniswap_ethereum_2022_02_24.xlsx', 'uniswap_ethereum_2022_02_25.xlsx', 'uniswap_ethereum_2022_02_26.xlsx', 'uniswap_ethereum_2022_02_27.xlsx', 'uniswap_ethereum_2022_02_28.xlsx']

In [10]:
df1 = pd.read_excel(dir_path+"/"+"uniswap_ethereum_2022_02_01.xlsx")
df1.head()

,ID,Transaction ID,Timestamp,Timestamp (Unix),Pool,Sender,Recipient,Origin,Token 0 Symbol,Token 1 Symbol,Token 0,Token 1,SqrticeX96,Tick,Log Index,Amount 0 (Excel),Amount 1 (Excel),Amount USD (Excel)
0,0x0009e97e64dd389754cc04e74cd4c5c53dd5ae9e5d12...,0x0009e97e64dd389754cc04e74cd4c5c53dd5ae9e5d12...,2022-02-01 01:01:03,1643706063,0x88e6a0c2ddd26feeb64f039a2c41296fcb3f5640,0xc7ee7c66636f407586afa431c19a916e04928942,0x6279653c28f138c8b31b8a0f6f8cd2c58e8c1705,0xff1651fb758e92adfb44632db5b42f56da9ad70d,USDC,WETH,0xa0b86991c6218b36c1d19d4a2e9eb0ce3606eb48,0xc02aaa39b223fe8d0a0e5c4f27ead9083c756cc2,NaN,196953,93,-18644.207093,6.666764,18618.281612
1,0x0009e97e64dd389754cc04e74cd4c5c53dd5ae9e5d12...,0x0009e97e64dd389754cc04e74cd4c5c53dd5ae9e5d12...,2022-02-01 01:01:03,1643706063,0xfca9090d2c91e11cc546b0d7e4918c79e0088194,0xc7ee7c66636f407586afa431c19a916e04928942,0xc7ee7c66636f407586afa431c19a916e04928942,0xff1651fb758e92adfb44632db5b42f56da9ad70d,XSGD,WETH,0x70e8de73ce538da2beed35d14187f6959a8eca96,0xc02aaa39b223fe8d0a0e5c4f27ead9083c756cc2,NaN,193992,95,25192.349866,-6.714320,18724.981487
2,0x0009e97e64dd389754cc04e74cd4c5c53dd5ae9e5d12...,0x0009e97e64dd389754cc04e74cd4c5c53dd5ae9e5d12...,2022-02-01 01:01:03,1643706063,0x6279653c28f138c8b31b8a0f6f8cd2c58e8c1705,0xc7ee7c66636f407586afa431c19a916e04928942,0xfca9090d2c91e11cc546b0d7e4918c79e0088194,0xff1651fb758e92adfb44632db5b42f56da9ad70d,XSGD,USDC,0x70e8de73ce538da2beed35d14187f6959a8eca96,0xa0b86991c6218b36c1d19d4a2e9eb0ce3606eb48,NaN,-3015,94,-25192.349866,18644.207093,18644.207093
3,0x001217318799b558737c0e388fd23764f991657aaa7b...,0x001217318799b558737c0e388fd23764f991657aaa7b...,2022-02-01 21:29:11,1643779751,0x88e6a0c2ddd26feeb64f039a2c41296fcb3f5640,0x68b3465833fb72a70ecdf485e0e4c7bd8665fc45,0x68b3465833fb72a70ecdf485e0e4c7bd8665fc45,0x91231de73c6b0a6b990ed38b81423a33b3a064f3,USDC,WETH,0xa0b86991c6218b36c1d19d4a2e9eb0ce3606eb48,0xc02aaa39b223fe8d0a0e5c4f27ead9083c756cc2,NaN,197113,421,50.000000,-0.018149,50.052895
4,0x001728974803a16baecc6f3a06e76ebf24abbcf0171d...,0x001728974803a16baecc6f3a06e76ebf24abbcf0171d...,2022-02-01 05:21:39,1643721699,0x88e6a0c2ddd26feeb64f039a2c41296fcb3f5640,0x1111111254fb6c44bac0bed2854e76f90643097d,0xf0b3ed341884f2383d76badf024f314e12c9a745,0xf0b3ed341884f2383d76badf024f314e12c9a745,USDC,WETH,0xa0b86991c6218b36c1d19d4a2e9eb0ce3606eb48,0xc02aaa39b223fe8d0a0e5c4f27ead9083c756cc2,NaN,196981,119,-5267.827473,1.888975,5263.543744

In [11]:
df1.tail()

,ID,Transaction ID,Timestamp,Timestamp (Unix),Pool,Sender,Recipient,Origin,Token 0 Symbol,Token 1 Symbol,Token 0,Token 1,SqrticeX96,Tick,Log Index,Amount 0 (Excel),Amount 1 (Excel),Amount USD (Excel)
23560,0xffef4b077cbcf80e178383db7019d780736d10a4dc81...,0xffef4b077cbcf80e178383db7019d780736d10a4dc81...,2022-02-01 06:45:00,1643726700,0x88e6a0c2ddd26feeb64f039a2c41296fcb3f5640,0x51399b32cd0186bb32230e24167489f3b2f47870,0x51399b32cd0186bb32230e24167489f3b2f47870,0x281c662752d5ac41cf1c74fb92595794805ad674,USDC,WETH,0xa0b86991c6218b36c1d19d4a2e9eb0ce3606eb48,0xc02aaa39b223fe8d0a0e5c4f27ead9083c756cc2,NaN,197056,15,-454878.559571,164.267870,455522.004467
23561,0xfff18c9098d3fe757bb3e506510c03e88f0b7c8ef35e...,0xfff18c9098d3fe757bb3e506510c03e88f0b7c8ef35e...,2022-02-01 12:03:19,1643745799,0x3782a3425cd093d5cd0c5b684be72641e199029c,0x68b3465833fb72a70ecdf485e0e4c7bd8665fc45,0xa4fb0e1f6ad0a87a3ec2427ca3a944c42d19d1ca,0xa4fb0e1f6ad0a87a3ec2427ca3a944c42d19d1ca,BYTES,WETH,0x7d647b1a0dcd5525e9c6b3d14be58f27674f8c95,0xc02aaa39b223fe8d0a0e5c4f27ead9083c756cc2,NaN,-40826,98,-117.941668,2.000000,5523.733855
23562,0xfff3e692ff4f3ba88cd1f46231d449dde0399841d9e8...,0xfff3e692ff4f3ba88cd1f46231d449dde0399841d9e8...,2022-02-01 21:55:18,1643781318,0x88e6a0c2ddd26feeb64f039a2c41296fcb3f5640,0x68b3465833fb72a70ecdf485e0e4c7bd8665fc45,0x68b3465833fb72a70ecdf485e0e4c7bd8665fc45,0x88566483155b7f5d18b2f9cfeaa1820288db4e11,USDC,WETH,0xa0b86991c6218b36c1d19d4a2e9eb0ce3606eb48,0xc02aaa39b223fe8d0a0e5c4f27ead9083c756cc2,NaN,197093,544,22984.154867,-8.326441,22986.071479
23563,0xfff3e692ff4f3ba88cd1f46231d449dde0399841d9e8...,0xfff3e692ff4f3ba88cd1f46231d449dde0399841d9e8...,2022-02-01 21:55:18,1643781318,0x537a0a5654045c52ec45c4c86ed0c1ffe893809d,0x68b3465833fb72a70ecdf485e0e4c7bd8665fc45,0x68b3465833fb72a70ecdf485e0e4c7bd8665fc45,0x88566483155b7f5d18b2f9cfeaa1820288db4e11,NaN,USDC,0x41f7b8b9b897276b7aae926a9016935280b44e97,0xa0b86991c6218b36c1d19d4a2e9eb0ce3606eb48,NaN,-34,541,23050.000000,-22984.154867,22984.154867
23564,0xfff78cf71eb6a261000e9c9eb4e87038917825238811...,0xfff78cf71eb6a261000e9c9eb4e87038917825238811...,2022-02-01 11:53:40,1643745220,0x88e6a0c2ddd26feeb64f039a2c41296fcb3f5640,0xe592427a0aece92de3edee1f18e0157c05861564,0x56178a0d5f301baf6cf3e1cd53d9863437345bf9,0x065e3dbafcb2c26a978720f9eb4bce6ad9d644a1,USDC,WETH,0xa0b86991c6218b36c1d19d4a2e9eb0ce3606eb48,0xc02aaa39b223fe8d0a0e5c4f27ead9083c756cc2,NaN,197106,3,416159.172262,-150.995568,416594.419217

In [12]:
files = res

In [13]:
df =df1
from tqdm import tqdm
for file in tqdm(files): 
    # combining multiple excel worksheets 
    # into single data frames
    df = pd.concat([df, pd.read_excel(dir_path+"/"+file)],
                   ignore_index=True, sort=False)

100%|██████████| 28/28 [04:50<00:00, 10.38s/it]

In [14]:
df_Eth_Feb = df
df_Eth_Feb.tail()

,ID,Transaction ID,Timestamp,Timestamp (Unix),Pool,Sender,Recipient,Origin,Token 0 Symbol,Token 1 Symbol,Token 0,Token 1,SqrticeX96,Tick,Log Index,Amount 0 (Excel),Amount 1 (Excel),Amount USD (Excel)
902985,0xffee09fd973d9b418248bf4b403b985c2cbbd1a4242e...,0xffee09fd973d9b418248bf4b403b985c2cbbd1a4242e...,2022-02-28 12:00:43,1646078443,0xe859041c9c6d70177f83de991b9d757e13cea26e,0x68b3465833fb72a70ecdf485e0e4c7bd8665fc45,0xd9a224e05b486e2b07521f1d55fe68bbee7375b4,0xd9a224e05b486e2b07521f1d55fe68bbee7375b4,HDRN,USDC,0x3819f64f282bf135d62168c1e513280daf905e06,0xa0b86991c6218b36c1d19d4a2e9eb0ce3606eb48,NaN,-205353,399,-4.160000e+07,50.753178,50.753178
902986,0xffeecb154b8d10f34e25394e9607871a72299c69ec7b...,0xffeecb154b8d10f34e25394e9607871a72299c69ec7b...,2022-02-28 08:22:48,1646065368,0x34b8487fc2912c486b04d1436b07f19f7730cd43,0x68b3465833fb72a70ecdf485e0e4c7bd8665fc45,0x5bdac7f9714d983287240468c2d6cd0f8f1fe3e1,0x5bdac7f9714d983287240468c2d6cd0f8f1fe3e1,WETH,POLK,0xc02aaa39b223fe8d0a0e5c4f27ead9083c756cc2,0xd478161c952357f05f0292b56012cd8457f1cfbf,NaN,96258,43,1.000000e+00,-15215.616466,2808.993688
902987,0xfffe6504a45bfbff9916e64aa79fa36163a343528ad1...,0xfffe6504a45bfbff9916e64aa79fa36163a343528ad1...,2022-02-28 10:17:32,1646072252,0x60594a405d53811d3bc4766596efd80fd545a270,0xe592427a0aece92de3edee1f18e0157c05861564,0xe592427a0aece92de3edee1f18e0157c05861564,0xd0612c759fc6c512b7c3abceb2366c4f4096451c,DAI,WETH,0x6b175474e89094c44da98b954eedeac495271d0f,0xc02aaa39b223fe8d0a0e5c4f27ead9083c756cc2,NaN,-79458,154,1.699211e+03,-0.601838,1697.209209
902988,0xffff66aabc70fea40c0b14052e01128574e47d7f021a...,0xffff66aabc70fea40c0b14052e01128574e47d7f021a...,2022-02-28 16:18:44,1646093924,0xeb5c52e8af57334fab0b5f3d888990c108545527,0xe592427a0aece92de3edee1f18e0157c05861564,0x3c24d656935e3424f4d0a0971b986277cb0d797e,0xd63da994f5db37f4e97141c051426b3c92d804f5,WETH,WRLD,0xc02aaa39b223fe8d0a0e5c4f27ead9083c756cc2,0xd5d86fc8d5c0ea1ac1ac5dfab6e529c9967a45e9,NaN,96499,72,1.699380e+00,-26194.137982,5009.016108
902989,0xffff66aabc70fea40c0b14052e01128574e47d7f021a...,0xffff66aabc70fea40c0b14052e01128574e47d7f021a...,2022-02-28 16:18:44,1646093924,0x11b815efb8f581194ae79006d24e0d814b7697f6,0xe592427a0aece92de3edee1f18e0157c05861564,0xe592427a0aece92de3edee1f18e0157c05861564,0xd63da994f5db37f4e97141c051426b3c92d804f5,WETH,USDT,0xc02aaa39b223fe8d0a0e5c4f27ead9083c756cc2,0xdac17f958d2ee523a2206206994597c13d831ec7,NaN,-196456,69,-1.699380e+00,5000.000000,5001.440868

In [15]:
df_Eth_Feb.to_csv("Eth_Feb.csv")

In [16]:
df_Eth_Feb = pd.read_csv("Eth_Feb.csv")

In [17]:
Eth_Amount_Feb = df_Eth_Feb[["Timestamp", "Amount USD (Excel)"]]

In [18]:
Eth_Amount_Feb.columns =['Timestamp', 'Amount_USD']
Eth_Amount_Feb

                  Timestamp    Amount_USD
0       2022-02-01 01:01:03  18618.281612
1       2022-02-01 01:01:03  18724.981487
2       2022-02-01 01:01:03  18644.207093
3       2022-02-01 21:29:11     50.052895
4       2022-02-01 05:21:39   5263.543744
...                     ...           ...
902985  2022-02-28 12:00:43     50.753178
902986  2022-02-28 08:22:48   2808.993688
902987  2022-02-28 10:17:32   1697.209209
902988  2022-02-28 16:18:44   5009.016108
902989  2022-02-28 16:18:44   5001.440868

[902990 rows x 2 columns]

In [19]:
Eth_Amount_Feb['Timestamp']=pd.to_datetime(Eth_Amount_Feb['Timestamp'])
Eth_Amount_Feb.dtypes

<ipython-input-19-9cb6e02799da>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  Eth_Amount_Feb['Timestamp']=pd.to_datetime(Eth_Amount_Feb['Timestamp'])

Timestamp     datetime64[ns]
Amount_USD           float64
dtype: object

In [20]:
Eth_Amount_Feb=Eth_Amount_Feb.sort_values(by='Timestamp')
Eth_Amount_Feb

                 Timestamp     Amount_USD
21765  2022-02-01 00:00:41  300254.255812
18368  2022-02-01 00:00:41  101558.874168
45330  2022-02-01 00:00:41  300254.255812
10141  2022-02-01 00:00:41   38660.453059
18369  2022-02-01 00:00:41  101604.350712
...                    ...            ...
881633 2022-02-28 23:59:39     700.509239
892696 2022-02-28 23:59:39    2921.335970
892670 2022-02-28 23:59:39   13727.280130
874280 2022-02-28 23:59:50     172.163855
874279 2022-02-28 23:59:50     172.289490

[902990 rows x 2 columns]

In [21]:
Eth_Amount_Feb.to_csv("Eth_Amount_Feb.csv")